### ISSUE TITLE
license and linking and L

### ISSUE THREAD

**Issue by loriab** [simint-chem/simint-generator#1]
- [x] You might want to slap a license and readme file in here, if only to point to http://www.bennyp.org/research/simint/
- [x] Your `SIMINT_LINK_FLAGS` isn't making it to the final link.txt, so [this and co.](https://github.com/simint-chem/simint-generator/blob/master/skel/cmake/DefaultFlags.cmake#L15) are having no impression. And I can't fake it with `SIMINT_C_FLAGS` either. _Can_ fake it with `CMAKE_C_FLAGS`.
- [x] Requesting an AM beyond which it's prepared to go gives nothing much of an error msg:
```
--            Maximum AM: 6
--    Maximum Derivative: 0
--         CMAKE_C_FLAGS: -gcc-name=/theoryfs2/ds/cdsgroup/miniconda/envs/text35/bin/gcc -xHost
--       CMAKE_CXX_FLAGS: -gcc-name=/theoryfs2/ds/cdsgroup/miniconda/envs/text35/bin/gcc -gxx-name=/theoryfs2/ds/cdsgroup/miniconda/envs/text35/bin/g++ -xHost
--     SIMINT_C_INCLUDES: /theoryfs2/ds/cdsgroup/psi4-compile/hrw-temp/objdir53/external/upstream/simint/simint_external-prefix/src/simint_external;/theoryfs2/ds/cdsgroup/psi4-compile/hrw-temp/objdir53/external/upstream/simint/simint_external-prefix/src/simint_external-build/stage
--        SIMINT_C_FLAGS: -std=c99;-qopenmp;-qopt-report=5;-w3;-wd10397;-wd2415;-wd981;-wd869;-wd177;-mssse3
--     SIMINT_LINK_FLAGS: -qopenmp
CMake Error at simint/CMakeLists.txt:11 (file):
  file failed to open for reading (No such file or directory):

    /theoryfs2/ds/cdsgroup/psi4-compile/hrw-temp/objdir53/external/upstream/simint/simint_external-prefix/src/simint_external/simint/ostei/gen/filelist_d0_6
```
- [x] You'll want lines like [this](https://github.com/psi4/libint/blob/master/cmake/libintConfig.cmake.in#L25) and [this](https://github.com/psi4/libint/blob/master/cmake/libintConfig.cmake.in#L46) in simintConfig.

- [x] Any code that intefaces with simint is going to have to have [restrict](https://github.com/psi4/libint/blob/master/cmake/libintConfig.cmake.in#L46), right? So why not have that def be an interface property of `simint::simint` and allow the maximum ignorance on the part of the interfacer. And you know how I feel about which side should define `USING_simint`. :-)

**Comment by bennybp** [comment]
Ok some fixed. I had tried to fix the linking issue before, but I guess I missed one.

I moved handling of restrict to the header files themselves. I usually hate requiring command line arguments to use a library (to the extent that it is possible).

**Comment by loriab** [comment]
Thanks! That means I should kill off [this restrict](https://github.com/loriab/psi4/blob/ebd87906df7d2383933beaf6c9898aee71cec8e2/psi4/src/psi4/libmints/CMakeLists.txt#L72), right? Or are you going to do that after I push the PR branch?

Also, can I get confirmation that the tarball has been rebuilt from generator? If so, I'll try the conda package again, without hacks.

**Comment by bennybp** [comment]
Yes. I was planning on doing that after your rebase, but you can do that if you'd like.

And yes I just rebuilt the tarball so give it a try

**Comment by loriab** [comment]
Confirm that both conda pkgs built, btw, and that the linking for STANDALONE works now. https://anaconda.org/psi4/simint/files . Will test those after you've made whatever changes you plan to the psi4 PR.

**Comment by bennybp** [comment]
Are those really v0.6 or are they the semi-hidden 0.7? I will probably do an official release of 0.7 in the next day or so

**Comment by loriab** [comment]
Oh, yeah, they're really 0.7 (https://github.com/psi4/psi4meta/blob/master/conda-recipes/simint/meta.yaml#L9). I just didn't want to be up to 0.7build23 by the time it's ready for public consumption.

Great on the 0.7 release. Will that have expanded AMs? And you'll have to tell me if you bump the tarball behind the scenes so I can roll a new package, since I can't see its changes.
